services:
  - type: web
    name: resume-skill-extractor-job-matcher
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: SECRET_KEY
        value: your-secret-key-here
